-- Test fixture tables for Supabase reference validation
-- Used by run-supabase-tests.js against local Supabase

-- ── PRIVATE SCHEMA (for schema-switching tests) ──
CREATE SCHEMA IF NOT EXISTS private;

-- ── DATA TABLES (public schema) ──

-- Characters (basic select/filter tests)
DROP TABLE IF EXISTS characters CASCADE;
CREATE TABLE characters (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    age INTEGER,
    species TEXT
);
INSERT INTO characters (name, age, species) VALUES
    ('Luke', 25, 'Human'),
    ('Leia', 25, 'Human'),
    ('Han', 35, 'Human'),
    ('Yoda', 900, 'Yoda species'),
    ('Chewbacca', 200, 'Wookiee');

-- Countries/Cities (FK relation tests, also used for order-on-referenced, limit-on-referenced)
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS countries CASCADE;
CREATE TABLE countries (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);
CREATE TABLE cities (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    country_id INTEGER REFERENCES countries(id)
);
INSERT INTO countries (name) VALUES ('France'), ('Japan'), ('USA');
INSERT INTO cities (name, country_id) VALUES
    ('Paris', 1), ('Lyon', 1), ('Tokyo', 2), ('Osaka', 2), ('New York', 3);

-- Contacts (array/null filter tests)
DROP TABLE IF EXISTS contacts CASCADE;
CREATE TABLE contacts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    email TEXT,
    status TEXT DEFAULT 'active',
    tags TEXT[]
);
INSERT INTO contacts (name, email, status, tags) VALUES
    ('Alice', 'alice@example.com', 'active', '{"friend","work"}'),
    ('Bob', 'bob@example.com', 'active', '{"family"}'),
    ('Charlie', 'charlie@example.com', 'inactive', '{"work"}'),
    ('Diana', 'diana@example.com', 'active', '{"friend","family"}');

-- Players (ordering/pagination tests)
DROP TABLE IF EXISTS players CASCADE;
CREATE TABLE players (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    score INTEGER DEFAULT 0
);
INSERT INTO players (name, score) VALUES
    ('Alice', 100), ('Bob', 200), ('Charlie', 150), ('Diana', 300);

-- Products (JSON tests)
DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price NUMERIC,
    category TEXT,
    metadata JSONB
);
INSERT INTO products (name, price, category, metadata) VALUES
    ('Widget', 9.99, 'gadgets', '{"color": "blue", "weight": 100}'),
    ('Gadget', 19.99, 'gadgets', '{"color": "red", "weight": 200}'),
    ('Doohickey', 4.99, 'tools', '{"color": "green", "weight": 50}');

-- Messages (for RPC tests)
DROP TABLE IF EXISTS messages CASCADE;
CREATE TABLE messages (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
INSERT INTO messages (content) VALUES ('Hello'), ('World');

-- ── PHASE 3: Tables for select/modifier tests ──

-- Table with spaces in name + FK relation (test #4: query-referenced-tables-with-spaces)
DROP TABLE IF EXISTS "profile details" CASCADE;
DROP TABLE IF EXISTS "user profiles" CASCADE;
CREATE TABLE "user profiles" (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "first name" TEXT NOT NULL
);
CREATE TABLE "profile details" (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profile_id INTEGER REFERENCES "user profiles"(id),
    bio TEXT
);
INSERT INTO "user profiles" ("first name") VALUES ('John'), ('Jane'), ('Bob');
INSERT INTO "profile details" (profile_id, bio) VALUES
    (1, 'Developer'), (2, 'Designer'), (3, 'Manager');

-- Junction table (test #5: query-referenced-tables-through-a-join-table)
DROP TABLE IF EXISTS student_classes CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS students CASCADE;
CREATE TABLE students (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);
CREATE TABLE classes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);
CREATE TABLE student_classes (
    student_id INTEGER REFERENCES students(id),
    class_id INTEGER REFERENCES classes(id),
    PRIMARY KEY (student_id, class_id)
);
INSERT INTO students (name) VALUES ('Alice'), ('Bob'), ('Charlie');
INSERT INTO classes (name) VALUES ('Math'), ('Science'), ('Art');
INSERT INTO student_classes (student_id, class_id) VALUES
    (1, 1), (1, 2), (2, 1), (2, 3), (3, 2), (3, 3);

-- Dual-FK table (test #6: query the same referenced table multiple times)
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
CREATE TABLE teams (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);
CREATE TABLE matches (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    home_team_id INTEGER REFERENCES teams(id),
    away_team_id INTEGER REFERENCES teams(id),
    home_score INTEGER DEFAULT 0,
    away_score INTEGER DEFAULT 0
);
INSERT INTO teams (name) VALUES ('Lakers'), ('Celtics'), ('Bulls');
INSERT INTO matches (home_team_id, away_team_id, home_score, away_score) VALUES
    (1, 2, 105, 98),
    (2, 3, 88, 92),
    (3, 1, 110, 100);

-- Private schema profiles (test #12: switching schemas per query)
DROP TABLE IF EXISTS private.profiles CASCADE;
CREATE TABLE private.profiles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id TEXT,
    display_name TEXT,
    secret_data TEXT
);
INSERT INTO private.profiles (user_id, display_name, secret_data) VALUES
    ('user-1', 'Alice', 'secret-1'),
    ('user-2', 'Bob', 'secret-2');

-- Grant anon access to private schema
GRANT USAGE ON SCHEMA private TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA private TO anon, authenticated;

-- ── RLS TEST TABLE ──
-- Used for RLS policy tests (#622-#630). Has restrictive policies that
-- demonstrate auth.uid(), auth.role(), auth.email(), auth.jwt() usage.
DROP TABLE IF EXISTS rls_todos CASCADE;
CREATE TABLE rls_todos (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id TEXT NOT NULL,
    email TEXT,
    role TEXT DEFAULT 'user',
    title TEXT NOT NULL,
    completed BOOLEAN DEFAULT false
);
INSERT INTO rls_todos (user_id, email, role, title, completed) VALUES
    ('test-user-1', 'owner@example.com', 'admin', 'Admin todo', false),
    ('test-user-2', 'user@example.com', 'user', 'User todo', false),
    ('test-user-3', 'viewer@example.com', 'viewer', 'Viewer todo', true);

ALTER TABLE rls_todos ENABLE ROW LEVEL SECURITY;

-- RLS policy tests use specific policies:
-- policy-select: authenticated users can SELECT
-- policy-insert: users can INSERT (owner policy)
-- policy-update: only owner can UPDATE
-- policy-delete: only admin role can DELETE
-- auth.uid: rows filtered by auth.uid()
-- auth.role: access based on role
-- auth.email: access based on email in JWT
-- auth.jwt: custom claims access

-- Default: no access (explicit policies below grant access)
-- SELECT: authenticated can see all
CREATE POLICY "rls_todos select" ON rls_todos FOR SELECT
    TO authenticated
    USING (true);

-- INSERT: any authenticated user can insert
CREATE POLICY "rls_todos insert" ON rls_todos FOR INSERT
    TO authenticated
    WITH CHECK (true);

-- UPDATE: only the owner (matching user_id) can update
CREATE POLICY "rls_todos update" ON rls_todos FOR UPDATE
    TO authenticated
    USING (auth.uid()::text = user_id);

-- DELETE: only the row owner can delete
CREATE POLICY "rls_todos delete" ON rls_todos FOR DELETE
    TO authenticated
    USING (auth.uid()::text = user_id);

-- Note: anon role has NO access to rls_todos (no anon policies).
-- This lets us test that anon gets blocked while authenticated works.

-- ── RPC FUNCTIONS ──
CREATE OR REPLACE FUNCTION hello_world()
RETURNS TEXT AS $$
BEGIN
    RETURN 'Hello, World!';
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_character_count()
RETURNS INTEGER AS $$
    SELECT COUNT(*) FROM characters;
$$ LANGUAGE sql;

CREATE OR REPLACE FUNCTION add_numbers(a INTEGER, b INTEGER)
RETURNS INTEGER AS $$
    SELECT a + b;
$$ LANGUAGE sql;

-- ── RLS ON DATA TABLES ──
-- Both anon and authenticated roles can read/write test tables.

ALTER TABLE characters ENABLE ROW LEVEL SECURITY;
ALTER TABLE countries ENABLE ROW LEVEL SECURITY;
ALTER TABLE cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE players ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "profile details" ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.profiles ENABLE ROW LEVEL SECURITY;

-- Allow anon to read and write all public test tables
CREATE POLICY "anon all characters" ON characters FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon all countries" ON countries FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon all cities" ON cities FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon all contacts" ON contacts FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon all players" ON players FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon all products" ON products FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon all messages" ON messages FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon all user profiles" ON "user profiles" FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon all profile details" ON "profile details" FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon all students" ON students FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon all classes" ON classes FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon all student_classes" ON student_classes FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon all teams" ON teams FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon all matches" ON matches FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon all private profiles" ON private.profiles FOR ALL TO anon USING (true) WITH CHECK (true);

-- Authenticated policies (same permissions)
CREATE POLICY "auth all characters" ON characters FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth all countries" ON countries FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth all cities" ON cities FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth all contacts" ON contacts FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth all players" ON players FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth all products" ON products FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth all messages" ON messages FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth all user profiles" ON "user profiles" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth all profile details" ON "profile details" FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth all students" ON students FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth all classes" ON classes FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth all student_classes" ON student_classes FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth all teams" ON teams FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth all matches" ON matches FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth all private profiles" ON private.profiles FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ── STORAGE RLS POLICIES ──
CREATE POLICY "Public buckets are viewable by everyone"
    ON storage.buckets FOR SELECT USING (true);
CREATE POLICY "Users can insert buckets (authenticated)"
    ON storage.buckets FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Users can update buckets (authenticated)"
    ON storage.buckets FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Users can delete buckets (authenticated)"
    ON storage.buckets FOR DELETE TO authenticated USING (true);

CREATE POLICY "Give public read access on public buckets"
    ON storage.objects FOR SELECT
    USING ((SELECT public FROM storage.buckets WHERE id = bucket_id) = true);
CREATE POLICY "Give public write access on public buckets"
    ON storage.objects FOR INSERT
    WITH CHECK ((SELECT public FROM storage.buckets WHERE id = bucket_id) = true);
CREATE POLICY "Authenticated users can upload"
    ON storage.objects FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update own files"
    ON storage.objects FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated users can delete own files"
    ON storage.objects FOR DELETE TO authenticated USING (true);
CREATE POLICY "Authenticated users can read objects"
    ON storage.objects FOR SELECT TO authenticated USING (true);
CREATE POLICY "Anon can download public files"
    ON storage.objects FOR SELECT TO anon
    USING ((SELECT public FROM storage.buckets WHERE id = bucket_id) = true);
